title: "Djamal Eddine Ouikene - CV"
email: d.ouikene@gmail.com
description: >- 
  Professional CV showcasing global leadership in IT and software development.
baseurl: "" 
url: "https://douikene.github.io/"
theme: minima
